### ISSUE TITLE
Executing `swifty-cli.exe` throws an error message

### ISSUE THREAD

**Issue by bux** [headswe/Swifty-Issue-Tracker#225]
Version: swifty-cli.exe v.4.0.0

Just executing `swifty-cli.exe` shows a part from the help text and then throws an error message:

```
C:\Users\jj\Desktop>swifty-cli.exe
## SWIFTY CLI ###
Version : 4.0.0.0

# COMMANDS
    Create
       Arguments
         repo config file path
         output folder
         --nocopy // (optional) only create the datafiles
        Exampel
         swifty-cli create C:\cool\repo.json C:\repoOut --nocopy
    Help
       This is help
    New
       Wizard for generateing a new repo.json
    Update

Unhandled Exception: System.NotImplementedException: The method or operation is not implemented.
   at Swifty_cli.Commands.Update.GetHelpString()
   at Swifty_cli.Commands.Help.Do(String[] args)
   at Swifty_cli.SwiftyCli.Run(String[] args)
   at Swifty_cli.Program.Main(String[] args)

```

**Comment by headswe** [comment]
Fixed in an upcoming version.
