### ISSUE TITLE
[error] Cannot download repo

### ISSUE THREAD

**Issue by adrenalinetooth** [headswe/Swifty-Issue-Tracker#227]
When attempting to download a repo, the following error is given:

System.FormatException: Input string was not in a correct format.
   at SwiftyWPF.RepositoryItem.WorkerOnDoWork(Object sender, DoWorkEventArgs doWorkEventArgs)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

https://i.gyazo.com/79ce533f73a694cb314f3cce0a1eb550.mp4
![image](https://user-images.githubusercontent.com/38298555/63191756-8d189700-c026-11e9-89ac-3f4a871f5995.png)
![image](https://user-images.githubusercontent.com/38298555/63191763-9144b480-c026-11e9-9a85-40f1c794ecfb.png)

**Comment by headswe** [comment]
The looks oddly formatted looks like a dot or something after .net
